server:
  port: 14800

spring:
  datasource:
    url: jdbc:mysql://rm-bp1275499403kh5u08o.mysql.rds.aliyuncs.com:3306/ikunfans?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: Xiaocaozhou2016(
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    minimum-idle: 5
    maximum-pool-size: 10
    auto-commit: true
    idle-timeout: 30000
    pool-name: DatebookHikariCP
    max-lifetime: 1800000
    connection-timeout: 30000

mybatis-plus:
  mapperLocations: ["classpath*:/Mapper/*.xml"]
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
